import type { Product } from "./types"

export const mockProducts: Product[] = [
  // Electronics - Smartphones
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    description: "Latest iPhone with A17 Pro chip, titanium design, and advanced camera system",
    price: 1199,
    originalPrice: 1299,
    discount: 8,
    category: "Electronics",
    subcategory: "Smartphones",
    brand: "Apple",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 2547,
    inStock: true,
    tags: ["smartphone", "apple", "5g", "camera", "premium"],
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra",
    description: "Flagship Android phone with S Pen, 200MP camera, and AI features",
    price: 1099,
    category: "Electronics",
    subcategory: "Smartphones",
    brand: "Samsung",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 1823,
    inStock: true,
    tags: ["smartphone", "samsung", "android", "s-pen", "camera"],
  },
  {
    id: "3",
    name: "Google Pixel 8 Pro",
    description: "AI-powered photography and pure Android experience",
    price: 899,
    originalPrice: 999,
    discount: 10,
    category: "Electronics",
    subcategory: "Smartphones",
    brand: "Google",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 1456,
    inStock: true,
    tags: ["smartphone", "google", "android", "ai", "photography"],
  },

  // Electronics - Laptops
  {
    id: "4",
    name: "MacBook Pro 16-inch M3",
    description: "Professional laptop with M3 chip, 18-hour battery life, and Liquid Retina XDR display",
    price: 2499,
    category: "Electronics",
    subcategory: "Laptops",
    brand: "Apple",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.9,
    reviews: 892,
    inStock: true,
    tags: ["laptop", "apple", "m3", "professional", "creative"],
  },
  {
    id: "5",
    name: "Dell XPS 13 Plus",
    description: "Ultra-thin laptop with 13th Gen Intel Core processors and stunning display",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    category: "Electronics",
    subcategory: "Laptops",
    brand: "Dell",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 634,
    inStock: true,
    tags: ["laptop", "dell", "ultrabook", "intel", "portable"],
  },
  {
    id: "6",
    name: "ASUS ROG Strix G15",
    description: "Gaming laptop with RTX 4070, AMD Ryzen 9, and 165Hz display",
    price: 1599,
    category: "Electronics",
    subcategory: "Laptops",
    brand: "ASUS",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.4,
    reviews: 1247,
    inStock: true,
    tags: ["laptop", "gaming", "asus", "rtx", "amd"],
  },

  // Electronics - Headphones
  {
    id: "7",
    name: "Sony WH-1000XM5",
    description: "Industry-leading noise canceling wireless headphones",
    price: 349,
    originalPrice: 399,
    discount: 13,
    category: "Electronics",
    subcategory: "Headphones",
    brand: "Sony",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 3421,
    inStock: true,
    tags: ["headphones", "sony", "noise-canceling", "wireless", "premium"],
  },
  {
    id: "8",
    name: "AirPods Pro (2nd Gen)",
    description: "Active noise cancellation, spatial audio, and MagSafe charging",
    price: 249,
    category: "Electronics",
    subcategory: "Headphones",
    brand: "Apple",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 5672,
    inStock: true,
    tags: ["earbuds", "apple", "noise-canceling", "wireless", "spatial-audio"],
  },
  {
    id: "9",
    name: "Bose QuietComfort 45",
    description: "Comfortable noise canceling headphones with 24-hour battery",
    price: 279,
    originalPrice: 329,
    discount: 15,
    category: "Electronics",
    subcategory: "Headphones",
    brand: "Bose",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 2134,
    inStock: true,
    tags: ["headphones", "bose", "noise-canceling", "comfortable", "long-battery"],
  },

  // Electronics - Tablets
  {
    id: "10",
    name: "iPad Pro 12.9-inch M2",
    description: "Ultimate iPad experience with M2 chip and Liquid Retina XDR display",
    price: 1099,
    category: "Electronics",
    subcategory: "Tablets",
    brand: "Apple",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 1567,
    inStock: true,
    tags: ["tablet", "apple", "m2", "professional", "creative"],
  },
  {
    id: "11",
    name: "Samsung Galaxy Tab S9 Ultra",
    description: "Large Android tablet with S Pen and desktop-class performance",
    price: 949,
    originalPrice: 1049,
    discount: 10,
    category: "Electronics",
    subcategory: "Tablets",
    brand: "Samsung",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 823,
    inStock: true,
    tags: ["tablet", "samsung", "android", "s-pen", "large-screen"],
  },

  // Home & Garden
  {
    id: "12",
    name: "Dyson V15 Detect",
    description: "Cordless vacuum with laser dust detection and powerful suction",
    price: 649,
    originalPrice: 749,
    discount: 13,
    category: "Home & Garden",
    subcategory: "Appliances",
    brand: "Dyson",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 2341,
    inStock: true,
    tags: ["vacuum", "cordless", "dyson", "cleaning", "laser-detection"],
  },
  {
    id: "13",
    name: "Instant Pot Duo 7-in-1",
    description: "Multi-use pressure cooker, slow cooker, rice cooker, and more",
    price: 89,
    originalPrice: 119,
    discount: 25,
    category: "Home & Garden",
    subcategory: "Kitchen",
    brand: "Instant Pot",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 8934,
    inStock: true,
    tags: ["kitchen", "pressure-cooker", "multi-use", "cooking", "instant-pot"],
  },
  {
    id: "14",
    name: "Ninja Foodi Personal Blender",
    description: "Compact blender for smoothies and protein shakes",
    price: 79,
    category: "Home & Garden",
    subcategory: "Kitchen",
    brand: "Ninja",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.4,
    reviews: 1567,
    inStock: true,
    tags: ["blender", "ninja", "smoothies", "compact", "personal"],
  },

  // Clothing & Fashion
  {
    id: "15",
    name: "Nike Air Max 270",
    description: "Comfortable running shoes with Max Air cushioning",
    price: 150,
    category: "Clothing & Fashion",
    subcategory: "Shoes",
    brand: "Nike",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 3456,
    inStock: true,
    tags: ["shoes", "nike", "running", "air-max", "comfortable"],
  },
  {
    id: "16",
    name: "Levi's 501 Original Jeans",
    description: "Classic straight-leg jeans with authentic fit and feel",
    price: 89,
    originalPrice: 109,
    discount: 18,
    category: "Clothing & Fashion",
    subcategory: "Clothing",
    brand: "Levi's",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.3,
    reviews: 2789,
    inStock: true,
    tags: ["jeans", "levis", "classic", "denim", "straight-leg"],
  },
  {
    id: "17",
    name: "Patagonia Better Sweater Fleece",
    description: "Warm and comfortable fleece jacket made from recycled materials",
    price: 119,
    category: "Clothing & Fashion",
    subcategory: "Clothing",
    brand: "Patagonia",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    tags: ["fleece", "patagonia", "sustainable", "warm", "outdoor"],
  },

  // Books
  {
    id: "18",
    name: "The Psychology of Money",
    description: "Timeless lessons on wealth, greed, and happiness by Morgan Housel",
    price: 16,
    originalPrice: 20,
    discount: 20,
    category: "Books",
    subcategory: "Business & Finance",
    brand: "Harriman House",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 12456,
    inStock: true,
    tags: ["book", "finance", "psychology", "money", "bestseller"],
  },
  {
    id: "19",
    name: "Atomic Habits",
    description: "An easy and proven way to build good habits and break bad ones",
    price: 14,
    originalPrice: 18,
    discount: 22,
    category: "Books",
    subcategory: "Self-Help",
    brand: "Avery",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.9,
    reviews: 23567,
    inStock: true,
    tags: ["book", "habits", "self-help", "productivity", "bestseller"],
  },
  {
    id: "20",
    name: "Dune",
    description: "Frank Herbert's epic science fiction masterpiece",
    price: 12,
    category: "Books",
    subcategory: "Science Fiction",
    brand: "Ace Books",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 8934,
    inStock: true,
    tags: ["book", "science-fiction", "classic", "dune", "epic"],
  },

  // Sports & Outdoors
  {
    id: "21",
    name: "Yeti Rambler 20oz Tumbler",
    description: "Insulated stainless steel tumbler that keeps drinks hot or cold",
    price: 35,
    category: "Sports & Outdoors",
    subcategory: "Drinkware",
    brand: "Yeti",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 5678,
    inStock: true,
    tags: ["tumbler", "yeti", "insulated", "stainless-steel", "outdoor"],
  },
  {
    id: "22",
    name: "REI Co-op Trail 25 Backpack",
    description: "Versatile daypack perfect for hiking and everyday use",
    price: 89,
    originalPrice: 109,
    discount: 18,
    category: "Sports & Outdoors",
    subcategory: "Backpacks",
    brand: "REI Co-op",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 1456,
    inStock: true,
    tags: ["backpack", "hiking", "rei", "outdoor", "daypack"],
  },

  // Beauty & Personal Care
  {
    id: "23",
    name: "CeraVe Moisturizing Cream",
    description: "Daily face and body moisturizer for dry to very dry skin",
    price: 19,
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    brand: "CeraVe",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 7890,
    inStock: true,
    tags: ["skincare", "moisturizer", "cerave", "dry-skin", "daily"],
  },
  {
    id: "24",
    name: "Oral-B Pro 1000 Electric Toothbrush",
    description: "Rechargeable electric toothbrush with pressure sensor",
    price: 49,
    originalPrice: 69,
    discount: 29,
    category: "Beauty & Personal Care",
    subcategory: "Oral Care",
    brand: "Oral-B",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.4,
    reviews: 3456,
    inStock: true,
    tags: ["toothbrush", "electric", "oral-b", "dental", "rechargeable"],
  },

  // Toys & Games
  {
    id: "25",
    name: "LEGO Creator 3-in-1 Deep Sea Creatures",
    description: "Build a shark, squid, or angler fish with this creative set",
    price: 79,
    category: "Toys & Games",
    subcategory: "Building Sets",
    brand: "LEGO",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    tags: ["lego", "building", "creative", "sea-creatures", "3-in-1"],
  },

  // Additional products to reach 100+
  {
    id: "26",
    name: "Amazon Echo Dot (5th Gen)",
    description: "Smart speaker with Alexa and improved sound quality",
    price: 49,
    originalPrice: 59,
    discount: 17,
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "Amazon",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 12345,
    inStock: true,
    tags: ["smart-speaker", "alexa", "amazon", "voice-control", "smart-home"],
  },
  {
    id: "27",
    name: "Fitbit Charge 5",
    description: "Advanced fitness tracker with built-in GPS and health metrics",
    price: 179,
    originalPrice: 199,
    discount: 10,
    category: "Electronics",
    subcategory: "Wearables",
    brand: "Fitbit",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.3,
    reviews: 4567,
    inStock: true,
    tags: ["fitness-tracker", "fitbit", "gps", "health", "wearable"],
  },
  {
    id: "28",
    name: "KitchenAid Stand Mixer",
    description: "Professional 5-quart stand mixer for all your baking needs",
    price: 379,
    originalPrice: 429,
    discount: 12,
    category: "Home & Garden",
    subcategory: "Kitchen",
    brand: "KitchenAid",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 6789,
    inStock: true,
    tags: ["mixer", "kitchenaid", "baking", "professional", "stand-mixer"],
  },
  {
    id: "29",
    name: "Adidas Ultraboost 22",
    description: "Premium running shoes with responsive Boost cushioning",
    price: 190,
    category: "Clothing & Fashion",
    subcategory: "Shoes",
    brand: "Adidas",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 2890,
    inStock: true,
    tags: ["shoes", "adidas", "running", "boost", "premium"],
  },
  {
    id: "30",
    name: "The Seven Husbands of Evelyn Hugo",
    description: "A captivating novel about a reclusive Hollywood icon",
    price: 13,
    originalPrice: 17,
    discount: 24,
    category: "Books",
    subcategory: "Fiction",
    brand: "Atria Books",
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.9,
    reviews: 45678,
    inStock: true,
    tags: ["book", "fiction", "hollywood", "novel", "bestseller"],
  },
]

// Add more products to reach 100+ (abbreviated for space)
for (let i = 31; i <= 100; i++) {
  const categories = ["Electronics", "Home & Garden", "Clothing & Fashion", "Books", "Sports & Outdoors"]
  const brands = ["Generic", "Premium", "Value", "Pro", "Elite"]
  const category = categories[i % categories.length]

  mockProducts.push({
    id: i.toString(),
    name: `Product ${i}`,
    description: `High-quality ${category.toLowerCase()} product with excellent features`,
    price: Math.floor(Math.random() * 500) + 20,
    category,
    subcategory: "General",
    brand: brands[i % brands.length],
    image: "/placeholder.svg?height=300&width=300",
    rating: Math.round((Math.random() * 2 + 3) * 10) / 10,
    reviews: Math.floor(Math.random() * 5000) + 100,
    inStock: Math.random() > 0.1,
    tags: ["product", category.toLowerCase().replace(" & ", "-"), "quality"],
  })
}

export function searchProducts(query: string, limit = 10): Product[] {
  const searchTerm = query.toLowerCase()

  const filtered = mockProducts.filter(
    (product) =>
      product.name.toLowerCase().includes(searchTerm) ||
      product.description.toLowerCase().includes(searchTerm) ||
      product.category.toLowerCase().includes(searchTerm) ||
      product.subcategory.toLowerCase().includes(searchTerm) ||
      product.brand.toLowerCase().includes(searchTerm) ||
      product.tags.some((tag) => tag.includes(searchTerm)),
  )

  return filtered.slice(0, limit)
}

export function getProductsByCategory(category: string, limit = 10): Product[] {
  const filtered = mockProducts.filter((product) => product.category.toLowerCase() === category.toLowerCase())

  return filtered.slice(0, limit)
}

export function getTopRatedProducts(limit = 10): Product[] {
  return mockProducts
    .filter((product) => product.inStock)
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit)
}

export function getBestDeals(limit = 10): Product[] {
  return mockProducts
    .filter((product) => product.discount && product.inStock)
    .sort((a, b) => (b.discount || 0) - (a.discount || 0))
    .slice(0, limit)
}

export function getProductsInPriceRange(min: number, max: number, limit = 10): Product[] {
  return mockProducts
    .filter((product) => product.price >= min && product.price <= max && product.inStock)
    .slice(0, limit)
}
